from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Protocol

from multilingual_rag_lab.domain.models import Chunk, Document, RetrievedChunk


class DocumentParser(Protocol):
    def parse(self, source: Path, file_type: str) -> object: ...


class Chunker(Protocol):
    def chunk(self, document_id: str, document: object) -> list[Chunk]: ...


class Embedder(Protocol):
    @property
    def dimension(self) -> int: ...
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class KnowledgeStore(Protocol):
    def upsert(self, chunks: Sequence[Chunk], vectors: Sequence[Sequence[float]]) -> None: ...
    def search(self, vector: Sequence[float], limit: int) -> list[RetrievedChunk]: ...
    def delete_document(self, document_id: str) -> None: ...
    def is_available(self) -> bool: ...


class DocumentRepository(Protocol):
    def save(self, document: Document, content: bytes) -> Path: ...
    def get(self, document_id: str) -> Document: ...
    def list(self) -> list[Document]: ...
    def delete(self, document_id: str) -> None: ...
    def source_path(self, document: Document) -> Path: ...


class Reranker(Protocol):
    def rerank(
        self, query: str, chunks: Sequence[RetrievedChunk], limit: int
    ) -> list[RetrievedChunk]: ...


class LLMPort(Protocol):
    def generate(self, question: str, context: str) -> str: ...
